In [23]:
import pandas as pd

In [110]:
import json
data = []
with open('./res.json') as f:
    for line in f.readlines():
        if line == '\n':
            continue
        data.append(json.loads(line))

In [111]:
df = pd.DataFrame(data)
df.id.nunique()

90986

In [57]:
# alternatief: https://www.gbif.org/occurrence/download?dataset_key=8a863029-f435-446a-821e-275f4f641165

,id,name,aantal,levensstadium,activiteit,locatie_id,locatie_name,waarnemer,gps,rds,tags
0,183729792,Fazant,1,onbekend,ter plaatse,/locations/17061/,Etten-Leur - Kelsdonk e.o. (NB),/users/4849/,"51.6033, 4.6310",102615 401871,"[algemeen, exoot]"
1,183722713,Fazant,1,onbekend,alarmerend,/locations/25452/,Breda - Lange Bunders en Slangwijk (NB),/users/3503/,"51.6399, 4.7364",109948 405874,"[algemeen, exoot]"
2,183722595,Fazant,1,onbekend,ter plaatse,/locations/25448/,Breda - Hooijdonk (NB),/users/3503/,"51.6363, 4.7301",109512 405479,"[algemeen, exoot]"
3,183723465,Fazant,1,onbekend,ter plaatse,/locations/19089/,Riel - Riels Laag - zuid (NB),/users/76659/,"51.4962, 5.0130",129013 389757,"[algemeen, exoot]"
4,183716661,Kip (verwilderd),2,onbekend,ter plaatse,/locations/13916/,Breda - Doornbos (NB),/users/191195/,"51.5964, 4.7992",114258 400997,"[vrij algemeen, exoot]"
...,...,...,...,...,...,...,...,...,...,...,...
4484,201668382,Bosuil,1,onbekend,roepend,/locations/134035/,Tilburg - De Blaak (NB),/users/59709/,"51.5482, 5.0373",130733 395527,"[vrij algemeen, inheems]"
4485,201621010,IJsvogel,1,onbekend,ter plaatse,/locations/2311/,Oudenbosch (NB),/users/129274/,"51.5867, 4.5172",94706 400119,"[vrij algemeen, inheems]"
4486,201637801,Grote Bonte Specht,1,onbekend,ter plaatse,/locations/25452/,Breda - Lange Bunders en Slangwijk (NB),/users/5547/,"51.6346, 4.7521",111035 405280,"[algemeen, inheems]"
4487,201656328,Grote Bonte Specht,1,onbekend,ter plaatse,/locations/17479/,Breda - 't Hout (NB),/users/17293/,"51.5600, 4.7532",111039 396977,"[algemeen, inheems]"
4488,201642559,Grote Bonte Specht,1,onbekend,ter plaatse,/locations/17023/,Tilburg - Huis ter Heide - Leikeven Uitkijktor...,/users/55278/,"51.6093, 5.0270",130050 402327,"[algemeen, inheems]"

In [68]:
with open('/home/simon/Downloads/occurrence.txt') as f:
    lines = f.readlines()[:100]

In [74]:
df = pd.read_csv('/home/simon/Downloads/occ-200.txt', sep='\t')
cols = df.columns

In [107]:
cols_i = ['identifier', 'modified', 'references', 'catalogNumber', 'individualCount', 'eventDate', 
          'eventTime', 'locality', 'decimalLatitude', 'decimalLongitude', 'scientificName', 'higherClassification','taxonKey', 'speciesKey']

In [109]:
i=23
df[cols[(i*10):(i+1)*10]].iloc[:10]

,genericName,acceptedScientificName,verbatimScientificName,typifiedName,protocol,lastParsed,lastCrawled,repatriated,relativeOrganismQuantity,recordedByID
0,Blicca,"Blicca bjoerkna (Linnaeus, 1758)",Blicca bjoerkna,NaN,DWC_ARCHIVE,2020-09-05T06:45:31.253Z,2020-08-19T12:31:07.894Z,False,NaN,NaN
1,Streptopelia,"Streptopelia decaocto (Frivaldszky, 1838)",Streptopelia decaocto,NaN,DWC_ARCHIVE,2020-09-05T06:45:32.608Z,2020-08-19T12:31:07.894Z,False,NaN,NaN
2,Streptopelia,"Streptopelia decaocto (Frivaldszky, 1838)",Streptopelia decaocto,NaN,DWC_ARCHIVE,2020-09-05T06:44:23.421Z,2020-08-19T12:31:07.894Z,False,NaN,NaN
3,Digitalis,Digitalis purpurea L.,Digitalis purpurea,NaN,DWC_ARCHIVE,2020-09-05T06:44:24.612Z,2020-08-19T12:31:07.894Z,False,NaN,NaN
4,Coloeus,"Coloeus monedula (Linnaeus, 1758)",Coloeus monedula,NaN,DWC_ARCHIVE,2020-09-05T06:45:37.361Z,2020-08-19T12:31:07.894Z,False,NaN,NaN
5,Chroicocephalus,"Chroicocephalus ridibundus (Linnaeus, 1766)",Chroicocephalus ridibundus,NaN,DWC_ARCHIVE,2020-09-05T06:45:37.404Z,2020-08-19T12:31:07.894Z,False,NaN,NaN
6,Erythromma,"Erythromma lindenii Selys, 1840",Erythromma lindenii,NaN,DWC_ARCHIVE,2020-09-05T06:45:40.491Z,2020-08-19T12:31:07.894Z,False,NaN,NaN
7,Erinaceus,"Erinaceus europaeus Linnaeus, 1758",Erinaceus europaeus,NaN,DWC_ARCHIVE,2020-09-05T06:44:32.366Z,2020-08-19T12:31:07.894Z,False,NaN,NaN
8,Sinapis,Sinapis arvensis L.,Sinapis arvensis,NaN,DWC_ARCHIVE,2020-09-05T06:44:31.209Z,2020-08-19T12:31:07.894Z,False,NaN,NaN
9,Ardea,"Ardea cinerea Linnaeus, 1758",Ardea cinerea,NaN,DWC_ARCHIVE,2020-09-05T06:44:33.461Z,2020-08-19T12:31:07.894Z,False,NaN,NaN

In [89]:
df.dataGeneralizations.iloc[1]

'WGS84 coordinates generalized with formula: `coord = floor(coord * 20) / 20`'